"""Demo-mode LLM client.

A drop-in replacement for :class:`orgos.llm.LLMClient` that makes NO
network calls. Returns deterministic, hand-curated artifacts so a user
can watch the entire UI flow — all 5 phases of progress, all 5 result
tabs, ZIP download — without spending any API tokens.

Why this exists:
  * Onboarding: new users can see what the tool does before getting a key.
  * Demos / screenshots / recordings.
  * CI-friendly: no network, no key, no flakes.
  * Faster iteration on the UI itself.

The demo project generated is a real, runnable Python CLI that prints
"Hello, <name>!" — small enough to be fully readable in the Files tab,
big enough to exercise every part of the UI (multi-file, per-domain
ownership, findings, fix loop).
"""

from __future__ import annotations

import asyncio
import logging
import re
from typing import Any, TypeVar

from pydantic import BaseModel

from .schemas import (
    FixOutput,
    Finding,
    GeneratedFile,
    ImplementerOutput,
    Plan,
    PlannedFile,
    ReviewOutput,
    Spec,
    TestFailure,
    TestRunResult,
)

logger = logging.getLogger(__name__)

T = TypeVar("T", bound=BaseModel)


# ── helpers ────────────────────────────────────────────────────────────


def _slugify(text: str) -> str:
    """Cheap, ASCII-safe slug. Falls back to 'demo-project' on empty input."""
    s = re.sub(r"[^a-zA-Z0-9\s-]", " ", text).strip().lower()
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    return (s[:40] or "demo-project").strip("-")


def _short(text: str, n: int = 80) -> str:
    text = text.strip().replace("\n", " ")
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


# ── canned content for the demo project ────────────────────────────────


def _spec_for(idea: str) -> Spec:
    name = _slugify(idea) + "-demo"
    return Spec(
        name=name,
        one_liner=f"[DEMO] {_short(idea, 80)}",
        description=(
            "This is a demo-mode artifact. No LLM was called.\n\n"
            "The orgos-team UI / CLI uses this canned Spec to drive the entire "
            "pipeline so you can see how Spec → Plan → Implement → Review → Fix "
            "phases connect. The actual project generated is a tiny runnable "
            "Python CLI (`hello`) — substantial enough to exercise the UI but "
            "small enough to read end-to-end in the Files tab.\n\n"
            f"Original idea you typed:\n{idea}"
        ),
        tech_stack=["Python 3.11", "Click 8.x", "pytest"],
        features=[
            "Prints 'Hello, world!' by default",
            "Accepts --name to greet a custom person",
            "Has a unit-test suite under tests/",
        ],
        non_goals=["Not a real production app", "No network calls"],
        acceptance_criteria=[
            "Running `python -m hello` prints 'Hello, world!'",
            "Running `python -m hello --name Alice` prints 'Hello, Alice!'",
            "All tests in tests/ pass under pytest",
        ],
    )


def _plan_for(spec: Spec) -> Plan:
    return Plan(
        project_name=spec.name,
        summary=spec.one_liner,
        files=[
            PlannedFile(
                path="hello/__init__.py",
                owner="backend",
                summary="Package init exposing greet().",
            ),
            PlannedFile(
                path="hello/__main__.py",
                owner="backend",
                summary="CLI entrypoint using Click.",
            ),
            PlannedFile(
                path="README.md",
                owner="devops",
                summary="Quick-start instructions.",
            ),
            PlannedFile(
                path=".env.example",
                owner="devops",
                summary="Empty example env file.",
            ),
            PlannedFile(
                path="requirements.txt",
                owner="devops",
                summary="Pinned runtime dependencies.",
            ),
            PlannedFile(
                path="tests/test_greet.py",
                owner="qa",
                summary="Unit tests for greet().",
            ),
        ],
        setup_commands=[
            "python -m venv .venv",
            "source .venv/bin/activate",
            "pip install -r requirements.txt",
        ],
        run_commands=[
            "python -m hello",
            "python -m hello --name Alice",
        ],
    )


_INIT_PY = '''"""hello — tiny demo package generated by orgos-team in demo mode."""

from __future__ import annotations

__all__ = ["greet"]


def greet(name: str = "world") -> str:
    """Return a friendly greeting."""
    return f"Hello, {name}!"
'''

_MAIN_PY = '''"""CLI entrypoint:  python -m hello [--name NAME] """

from __future__ import annotations

import click

from . import greet


@click.command()
@click.option("--name", default="world", help="Name to greet.")
def main(name: str) -> None:
    click.echo(greet(name))


if __name__ == "__main__":
    main()
'''

_README_MD = """# {project_name}

> Demo project generated by **orgos-team** in demo mode (no API calls).

## Quick start

```bash
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

python -m hello
python -m hello --name Alice
```

## Run tests

```bash
pytest -q
```
"""

_REQUIREMENTS_TXT = """click==8.1.7
pytest==8.3.3
"""

_TESTS_PY = '''"""Unit tests for hello.greet."""

from __future__ import annotations

from hello import greet


def test_default_greeting() -> None:
    assert greet() == "Hello, world!"


def test_custom_name() -> None:
    assert greet("Alice") == "Hello, Alice!"


def test_empty_name() -> None:
    assert greet("") == "Hello, !"
'''


def _impl_files(domain: str, project_name: str) -> ImplementerOutput:
    if domain == "backend":
        return ImplementerOutput(
            files=[
                GeneratedFile(
                    path="hello/__init__.py", content=_INIT_PY, owner="backend"
                ),
                GeneratedFile(
                    path="hello/__main__.py", content=_MAIN_PY, owner="backend"
                ),
            ],
            notes="Demo backend implementer.",
        )
    if domain == "devops":
        return ImplementerOutput(
            files=[
                GeneratedFile(
                    path="README.md",
                    content=_README_MD.format(project_name=project_name),
                    owner="devops",
                ),
                GeneratedFile(
                    path=".env.example",
                    content="# Demo project — no env vars required.\n",
                    owner="devops",
                ),
                GeneratedFile(
                    path="requirements.txt",
                    content=_REQUIREMENTS_TXT,
                    owner="devops",
                ),
            ],
            notes="Demo devops implementer.",
        )
    if domain == "qa":
        return ImplementerOutput(
            files=[
                GeneratedFile(
                    path="tests/test_greet.py", content=_TESTS_PY, owner="qa"
                )
            ],
            notes="Demo qa implementer.",
        )
    # frontend has no files in this demo plan
    return ImplementerOutput(files=[], notes="Demo project has no frontend.")


_DEMO_REVIEW = ReviewOutput(
    findings=[
        Finding(
            file="hello/__main__.py",
            line=11,
            severity="minor",
            rule="DOCSTRING",
            message="main() lacks a docstring describing the CLI surface.",
        ),
        Finding(
            file="tests/test_greet.py",
            line=15,
            severity="nit",
            rule="EDGE_CASE",
            message="test_empty_name asserts a slightly awkward output; consider strengthening.",
        ),
    ],
    summary="Demo review — looks clean overall, two small nits.",
)

_DEMO_SECURITY = ReviewOutput(
    findings=[
        Finding(
            file="requirements.txt",
            severity="nit",
            rule="DEP_PIN",
            message="Dependencies are pinned but consider a constraints.txt for transitive ones.",
        )
    ],
    summary="Demo security audit — no exploitable issues found.",
)


def _fix_for(domain: str, files: list[GeneratedFile]) -> FixOutput:
    if domain == "backend":
        # Address the docstring finding by patching __main__.py.
        patched = []
        for f in files:
            if f.path == "hello/__main__.py":
                patched.append(
                    GeneratedFile(
                        path=f.path,
                        owner="backend",
                        content=f.content.replace(
                            "@click.command()\n@click.option",
                            (
                                "@click.command()\n"
                                "@click.option"
                            ),
                        ).replace(
                            "def main(name: str) -> None:\n",
                            (
                                "def main(name: str) -> None:\n"
                                '    """Greet NAME (defaults to \'world\')."""\n'
                            ),
                        ),
                    )
                )
            else:
                patched.append(f)
        return FixOutput(
            files=patched,
            addressed_findings=["DOCSTRING on hello/__main__.py:11"],
            deferred_findings=[],
        )

    return FixOutput(
        files=list(files),
        addressed_findings=[],
        deferred_findings=[
            f"(no findings against {domain}'s files in demo)"
        ],
    )


# ── the client itself ──────────────────────────────────────────────────


class DemoLLMClient:
    """Stand-in for :class:`orgos.llm.LLMClient` — never touches the network.

    Same async signature (`call_structured(...)`, `close()`), so any code
    that types its dependency as `_ClientProto` (Chief does this) accepts
    it transparently.

    A small artificial delay per call makes the UI's live-progress
    animation actually animate. Set ``per_call_delay=0`` in tests.
    """

    def __init__(self, *, per_call_delay: float = 0.4) -> None:
        self.per_call_delay = per_call_delay
        self.calls: list[tuple[str, str]] = []
        # We need to remember the original idea so the demo Spec can
        # echo it back. The first product call captures it from
        # `user_message`.
        self._captured_idea: str = "(unknown idea)"

    async def call_structured(
        self,
        *,
        role: str,
        user_message: str,
        schema: type[T],
        **_kwargs: Any,
    ) -> T:
        self.calls.append((role, schema.__name__))

        if self.per_call_delay > 0:
            await asyncio.sleep(self.per_call_delay)

        if role == "product":
            # The user_message contains the original idea; extract it.
            m = re.search(r"---\n(.+?)\n---", user_message, re.DOTALL)
            if m:
                self._captured_idea = m.group(1).strip()
            return _spec_for(self._captured_idea)  # type: ignore[return-value]

        if role == "architect":
            spec = _spec_for(self._captured_idea)
            return _plan_for(spec)  # type: ignore[return-value]

        if role in ("backend", "frontend", "devops", "qa"):
            project_name = _slugify(self._captured_idea) + "-demo"
            if schema is ImplementerOutput:
                return _impl_files(role, project_name)  # type: ignore[return-value]
            if schema is FixOutput:
                # Pull the previous file contents out of the prompt? No —
                # we just return the canonical ones so the demo is
                # deterministic. The fixer prompt block contains them.
                base = _impl_files(role, project_name)
                return _fix_for(role, list(base.files))  # type: ignore[return-value]

        if role == "reviewer":
            return _DEMO_REVIEW  # type: ignore[return-value]
        if role == "security":
            return _DEMO_SECURITY  # type: ignore[return-value]

        raise AssertionError(
            f"DemoLLMClient does not know how to handle role={role!r} schema={schema.__name__}"
        )

    async def close(self) -> None:
        return None


class DemoTestRunner:
    """Stand-in for :class:`orgos.test_runner.TestRunner` — never spawns subprocesses.

    Returns a deterministic :class:`TestRunResult`. By default every call
    succeeds; if you construct it with ``fail_first_run=True`` the first
    call returns one canned failure (so you can demo the test → fix
    iteration without touching real code).
    """

    # Tell pytest this is NOT a test class (the "Test" suffix triggers collection on some versions).
    __test__ = False

    def __init__(
        self,
        *,
        per_call_delay: float = 0.3,
        fail_first_run: bool = False,
    ) -> None:
        self.per_call_delay = per_call_delay
        self.fail_first_run = fail_first_run
        self._call_count = 0

    async def run(self, files: list[GeneratedFile]) -> TestRunResult:
        self._call_count += 1
        if self.per_call_delay > 0:
            await asyncio.sleep(self.per_call_delay)

        if self.fail_first_run and self._call_count == 1:
            return TestRunResult(
                ran=True,
                passed=False,
                exit_code=1,
                failures=[
                    TestFailure(
                        test_name="test_default_greeting",
                        file_path="tests/test_greet.py",
                        error_excerpt=(
                            "AssertionError: expected 'Hello, world!' "
                            "got 'Hi, world!'"
                        ),
                    ),
                ],
                raw_output="(simulated test failure for demo)\n",
                duration_s=0.3,
            )

        return TestRunResult(
            ran=True,
            passed=True,
            exit_code=0,
            failures=[],
            raw_output="==== 3 passed in 0.04s ====\n",
            duration_s=0.3,
        )
